[tool.poetry]
name = "django-login-email"
version = "0.2.0"
description = ""
authors = ["svtter <svtter@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.4"
pycryptodome = "^3.20.0"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
homepage = "https://github.com/Svtter/django-login-email"
repository = "https://github.com/Svtter/django-login-email.git"
changelog = "https://github.com/Svtter/django-login-email/blob/master/CHANGELOG.md"
bugs = "https://github.com/Svtter/django-login-email/issues"
# sponsor = "https://github.com/sponsors/svtter"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "settings.settings"