# Generated by Django 5.1.4 on 2025-01-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_login_email', '0004_emailregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.DateTimeField(auto_now_add=True, verbose_name='Last register request time')),
                ('validated', models.BooleanField(default=False, verbose_name='Register Token validated')),
                ('mail_type', models.CharField(max_length=100, verbose_name='Mail type')),
                ('sault', models.CharField(max_length=100, verbose_name='Sault')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailLogin',
        ),
        migrations.DeleteModel(
            name='EmailRegister',
        ),
    ]
