name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # 添加权限配置
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx ghp-import sphinx_rtd_theme && pip install -e .

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Deploy to gh-pages
        run: |
          ghp-import -n -p -f docs/_build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
